### ISSUE TITLE
No waveform displayed in sample preview

### ISSUE THREAD

**Issue by ViktorNova** [harryhaaren/openAV-Fabla2#12]
I don't see a waveform for a pad with a loaded sample, just a flatline.
I am still able to change, e.g., the start time knob and see that same region updated.. just no wave displayed

**Comment by harryhaaren** [comment]
Hi Viktor, the waveform is temporarily disabled to aid debugging an ADSR issue. Thanks for noting here - I'll add it to the 2.0 milestone for release. 
Cheers! -Harry

**Comment by ViktorNova** [comment]
gotchya!
