### ISSUE TITLE
Sample Start acts as an on/off switch and Sample End does nothing

### ISSUE THREAD

**Issue by spectromas** [harryhaaren/openAV-Fabla2#19]
I'm guessing this might be related to the sample view being disabled and the sample length not being calculated because that perhaps but sample start dial mutes the sound of the sample on any other value than zero. I cannot make sample end make any difference to the sound at all. 

This is testing in Ardour, I don't currently have another host to try but can do if necessary.

**Comment by harryhaaren** [comment]
Hi, sample start / end is still WIP.
