### ISSUE TITLE
Make it possible to build without 'Desktop UI'

### ISSUE THREAD

**Issue by falkTX** [harryhaaren/openAV-Fabla2#28]
Hi Harry, hope everything goes well.
I have a small request for Fabla - make it possible to build without its native desktop UI.
Right now it requires cairo and Xlib which we do not have inside the MOD hardware.
The desktop UI is not usable inside the MOD hardware anyway.

Other things (ie, making it actually work on MOD) can be handled on separate bugs.
But for now it would be nice if it at least builds without UI.

Thanks in advance.

**Comment by harryhaaren** [comment]
Hey falkTX,

Yes of course - I'll add a build option just like ArtyFX has for this. I've built and used Fabla2 on the Quadra already - so there shouldn't be too much to fix. I probably need to push some changes up though.

I'll try get round to this over the weekend, Cheers, -Harry
