### ISSUE TITLE
No UI in Ardour 4

### ISSUE THREAD

**Issue by naught101** [harryhaaren/openAV-Fabla2#29]
cmake, make and make install run without errors, and everything appears to install correctly, but when I add the plugin to a channel in Ardour 4, and then double click it, I get this:

![fabla2_no_ui](https://cloud.githubusercontent.com/assets/167164/10012722/c28632bc-614d-11e5-9e46-19f56f395aa6.png)

ie. no UI at all. When I try right click and "edit with generic controls", I get this:

![fabla2_generic_ui](https://cloud.githubusercontent.com/assets/167164/10012735/f62f3686-614d-11e5-8eb9-28c147385327.png)

**Comment by naught101** [comment]
Let me know if there's any other info I can provide.

**Comment by harryhaaren** [comment]
Hey @naught101,

Thanks for the report. I wasn't aware that there is an issue with A4 and AVTK based UI's yet, so this is a new one. Once I get to a development machine, I'll grab latest A4, test and get back to you. 

Cheers, -Harry

**Comment by x42** [comment]
Do other LV2 plugin GUIs work in Ardour?
Ardour >  Help > About > Config    is   LV2 UI embedding: True   ?
Which version of Ardour is that?  Ardour binary from ardour.org?

**Comment by harryhaaren** [comment]
Hey @naught101, @x42,

Ardour4 from git, suil 0.8.2 -dev from debian 8.2 stable, works fine here:
![2015-09-22-210451_1140x750_scrot](https://cloud.githubusercontent.com/assets/106664/10030063/9fe9d536-616d-11e5-95af-7e14be38a231.png)

@naught101 : I guess we'll need the answers to the LV2 UI Embedding etc questions that x42 asked.
Cheers, -Harry

**Comment by naught101** [comment]
Yep, TAL Noizemaker works fine.
Yep, LV2 UI embedding: True
Ardour 4.2.0 from the KXStudio repos (running on kubuntu 15.04).

Is it possibly some conflict with Fabla 1? When I try to add that to a track and edit it, it crashes ardour completely.

**Comment by harryhaaren** [comment]
@naught101, you've built Fabla2 yourself right? What version of g++ / gcc do you have installed? Also, if the Help > Config box says, what version of g++ / gcc was Ardour4.2.0 on KX built with? There is a possible ABI breakage there.. same applies to Fabla1 crash issue.

Possible way of testing - build Ardour4 from git using the same gcc/g++ combo as the plugin and see if that crashes TAL but works with Fabla 1/2.

**Comment by naught101** [comment]
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-10ubuntu13' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 
```

The Ardour helpbox doesn't say anything about gcc/g++, the config says:

**Comment by naught101** [comment]
stupid tab key.

**Comment by harryhaaren** [comment]
Heh, no worries:

Output of
```
strings -a `which ardour4` | grep GCC
```
please?

**Comment by naught101** [comment]
Nothing. also with `grep -i`.

**Comment by naught101** [comment]
Perhaps @falktx could comment?

**Comment by harryhaaren** [comment]
naught101, version of suil? Last hope - if you're not on 0.8.2, upgrade it. Ardour is on suil-svn, I tried the 0.8.2 debian stable package.

You have gcc 4.9.2 locally, so Fabla2 is built with that. We need to find out if KXStudio is using 5.x for building or not, if yes possibly bug there. If no, who knows..

Gotta go to sleep here now, too late for debugging!

**Comment by naught101** [comment]
```
➜  ~  aptitude show libsuil-0-0
Package: libsuil-0-0                     
State: installed
Automatically installed: yes
Multi-Arch: same
Version: 0.8.2~dfsg0-1
Priority: optional
Section: universe/libs
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 112 k
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.24.0), libqtcore4 (>= 4:4.5.3), libqtgui4 (>= 4:4.5.3), libstdc++6 (>= 4.1.1)
PreDepends: multiarch-support
Breaks: libsuil-0-0 (!= 0.8.2~dfsg0-1)
Replaces: libsuil-0-0 (< 0.8.2~dfsg0-1)
Description: library for loading and wrapping LV2 plugin UIs
 Suil makes it possible to load a UI of any toolkit in a host using any other toolkit (assuming the toolkits are both supported by Suil). Hosts do not need to build against or link to foreign toolkit libraries
 to use UIs written with that toolkit (Suil performs its magic at runtime using dynamically loaded modules). The API is designed such that hosts do not need to explicitly support particular toolkits whatsoever
 - if Suil supports a particular toolkit, then all hosts that use Suil will support that toolkit "for free". Suil currently supports GTK-2+ and Qt4 
 
 This package provides the shared library.
Homepage: http://drobilla.net/software/suil/
```

**Comment by falkTX** [comment]
As per the recent change 8588b46f47ac250da37e69d7d8e7a31239fa4d3f, the UI is not being built unless specifically asked to.
```
option(BUILD_GUI              "Build GUI"                   OFF )
```
So I'd bet this is as simple as the UI not being enabled during build.

@harryhaaren you should probably leave the default as 'ON' ;)

**Comment by falkTX** [comment]
btw, if you're using kxstudio the suil version is useless since the ardour build is the official one - which includes its own suil libs.
also kxstudio libs build against suil statically, using suil-libs for the toolkit specific stuff.
No libsuil* stuff is ever used in kxstudio builds.

**Comment by naught101** [comment]
Sweet, thanks :)
