### ISSUE TITLE
Fabla2-git: GUI not available under host Carla

### ISSUE THREAD

**Issue by distrozapper** [harryhaaren/openAV-Fabla2#30]
Refers to commit fdde5d1d239dc5967319be19cfd6c26caf5e7cc3
Hi and thanks for these nice openAV tools!
Just FYI:
Today I gave Fabla2 git a try and I found it renders its GUI fine under ardour4, qtractor and jalv.gtk, but not under falktx's latest carla-git.
Carla complains about a deprecated feature requested by Fabla2 GUI:
Plugin UI requires a feature that is not supported:
http://lv2plug.in/ns/extensions/ui#makeSONameResident
I hope this can help improve.
Have a nice time!

**Comment by harryhaaren** [comment]
Thanks @distrozapper for reporting, appreciated! -Harry
