### ISSUE TITLE
Pads become invisible when closing the File dialog without loading a sample

### ISSUE THREAD

**Issue by ViktorNova** [harryhaaren/openAV-Fabla2#36]
This is consistent behaviour, the pads disappear when closing the file dialog by hitting Cancel or the escape key. The pads reappear when switching to the Live view and then back to the Pads view

**Comment by harryhaaren** [comment]
Fixed in https://github.com/harryhaaren/openAV-Fabla2/commit/a36eeeca4ea232133b3c9876330a79ec2693ef78
