### ISSUE TITLE
Sample loader 'File' button should not be visible from Live view

### ISSUE THREAD

**Issue by ViktorNova** [harryhaaren/openAV-Fabla2#37]
Having the File button visible in Live view is non-intuitive, since the pad to load the file onto cannot be selected. I think this button should either be hidden from Live view, or the ability to select a pad should be added to the live view. Even better, it would be more user friendly if "Load sample" was it's own button in the Pad view, maybe in the center above or below the pads, or to load the file picker by right-clicking the pads as in Fabla 1

Additionally, if the Live view is selected and the file button is clicked, it will return to pad view after either loading a sample or cancelling, which seems like odd behaviour.

**Comment by harryhaaren** [comment]
This is related to https://github.com/harryhaaren/openAV-Fabla2/issues/6, which will improve File loading and auditioning by providing the File-Browser directly in the UI. Again, this fancy feature is pushed out to 2.1.

The "change to pad view" is a quick-fix to not show the (currently blank) File-browser view.

Bug noted, added to 2.0, and the real fix will land in 2.1. Thanks
